# Generated by Django 5.1.2 on 2024-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherrequestshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='city_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название города'),
        ),
    ]
